### ISSUE TITLE
make possible to run it for a specific PR

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-webshots-tools#4]
- would take a list of `pr`s as an argument (e.g. in our case interested in only one ATM https://github.com/dandi/dandiarchive/pull/857 ATM)
- for each `{pr}`
  - `git checkout pr-{pr}`
  - get commit hexsha of current state of that PR
  - if that commit differs from recorded (if present in some side car file)
    - run webshots collection against `https://deploy-preview-{pr}--gui-dandiarchive-org.netlify.app/`
    - store commit hexsha in side car file
    - commit
  - git push (I guess we will configure to push all pr- branches in .git/config)

after implemented -- deploy cron job (to run frequently e.g. /5 min) on drogon to run against that 857 and push into dandi-api-webshots-PRs .

PS fancy optional feature -- add option to make script update status of the PR with a URL to that  repository/branch.  status - green if no errors

**Comment by jwodder** [comment]
@yarikoptic FYI: In the redesigned Dandiset pages, the "Metadata" button no longer has an ID, which means that the "edit-metadata" jobs all time out.

**Comment by jwodder** [comment]
@yarikoptic pr-857 branch in PR snapshots repo: https://github.com/dandi/dandi-api-webshots-prs/tree/pr-857

**Comment by jwodder** [comment]
@yarikoptic Cronjob set up on dandi@drogon.

**Comment by yarikoptic** [comment]
Thank you! Seems need little fixing when no changes
```
+ '[' 5f827788ad3580d72092705a0495ab8dce077386 '!=' 5f827788ad3580d72092705a0495ab8dce077386 ']'
+ 'No change to PR 857; doing nothing'
/home/dandi/cronlib/dandi-api-webshots-prs/tools/run-webshots-pr.sh: line 68: No change to PR 857; doing nothing: command not found
```

**Comment by jwodder** [comment]
@yarikoptic Fixed.

**Comment by mvandenburgh** [comment]
> @yarikoptic FYI: In the redesigned Dandiset pages, the "Metadata" button no longer has an ID, which means that the "edit-metadata" jobs all time out.

Ah, I didn't notice that when I was copying things over, it's fixed now.

**Comment by yarikoptic** [comment]
Sweet, https://github.com/dandi/dandi-api-webshots-prs labia any branch, needs push setting in .git/config I guess it just push --all

**Comment by yarikoptic** [comment]
We have https://github.com/dandi/dandi-api-webshots-prs/tree/pr-857 . Thank you @jwodder!
